name: CI
on: push
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: guestbook
          POSTGRES_DB: guestbook_test
          POSTGRES_PASSWORD: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.0
      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_HOST: postgres
          DATABASE_USER: guestbook
        run: |
          bin/rails db:setup
      - name: Run tests
        run: bin/rails test
